import Head from "next/head";
import Link from "next/link";
import styles from "../styles/index.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Design Token Sample App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.header}>
          <p>ACME</p>
        </div>
        <div>
          <h1 className={styles.h1}>HEADER (scss)</h1>
          <Link href="/">
          <button className={styles.btn}>BUTTON</button>
          </Link>
        </div>
      </main>
    </>
  );
}
